# Snowflake Production Pipeline

name: snowflake-pro-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [ main ]
    paths:
      - 'migrations/**'
      - '.github/workflows/snowflake-pro-pipeline.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Development:
    environment: Pro
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repo under $GITHUB_WORKSPACE, so the job can access it
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Python 3.8.x
          uses: actions/setup-python@v2.2.1
          with:
           python-version: 3.8.x

        - name: Run schemachange
          env:
            SF_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
            SF_USERNAME: ${{ secrets.SNOWFLAKE_USER }}
            SF_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
            SF_WAREHOUSE: ${{ secrets.SNOWFLAKE_WH }}
            SF_DATABASE: ${{ secrets.SNOWFLAKE_DB }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASS }}
          run: |
            echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
            python --version
            echo "Step 1: Installing schemachange"
            pip install schemachange

            echo "Step 2: Running schemachange"
            schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
